const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.TiledBg,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.wallclocktime,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Keyboard.Exps.StringFromKeyCode,
		C3.Plugins.Keyboard.Exps.LastKeyCode,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetBlur,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor
	];
};
self.C3_JsPropNameTable = [
	{Text: 0},
	{Sprite: 0},
	{鍵盤: 0},
	{Array: 0},
	{Text2: 0},
	{TTime: 0},
	{文本框: 0},
	{按鈕: 0},
	{TIntro: 0},
	{Tname: 0},
	{按鈕RE: 0},
	{平鋪背景: 0},
	{Tfrom: 0},
	{Browser: 0},
	{滑鼠: 0},
	{按鈕SW: 0},
	{Text_a_z: 0},
	{w: 0},
	{keyin: 0},
	{tt: 0},
	{name: 0}
];

self.InstanceType = {
	Text: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	鍵盤: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	Text2: class extends self.ITextInstance {},
	TTime: class extends self.ITextInstance {},
	文本框: class extends self.ITextInputInstance {},
	按鈕: class extends self.IButtonInstance {},
	TIntro: class extends self.ITextInstance {},
	Tname: class extends self.ITextInstance {},
	按鈕RE: class extends self.IButtonInstance {},
	平鋪背景: class extends self.ITiledBackgroundInstance {},
	Tfrom: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	滑鼠: class extends self.IInstance {},
	按鈕SW: class extends self.IButtonInstance {},
	Text_a_z: class extends self.ITextInstance {}
}